---


---

<h1 id="이벤트-이해하기">3.7 이벤트 이해하기</h1>
<p>이벤트는 진짜 이떤 일이 일어났을 때를 말한다!<br>
스크래치로 치면 방송하기…?</p>
<p>on(‘data’,콜백)이나 on(‘end’,콜백) 처럼 모듈 내부적으로 호출해 주는 이벤트도 있지만,<br>
우리가 직접 이벤트를 만들 수도 있다!</p>
<p>지금 보니까 내가 썻던 socket.io도 이벤트 기반으로 돌아가는 것 같다.(on, emit…)</p>
<blockquote>
<p>3장/event.js</p>
</blockquote>
<p>events 모듈을 사용한다. 모듈을 통해 생성한 객체는 이벤트 관리를 위한 메서드를 가지고 있다.|</p>

<table>
<thead>
<tr>
<th>메서드</th>
<th>설명</th>
</tr>
</thead>
<tbody>
<tr>
<td>on(이벤트명,콜백)</td>
<td>이벤트 이름과 이벤트 발생 시의 콜백 연결.</td>
</tr>
<tr>
<td>addListener(이벤트명, 콜백)</td>
<td>on과 같은 기능을 한다.(보통은 on쓰자)</td>
</tr>
<tr>
<td>emit(이벤트명)</td>
<td>이벤트를 호출하는 메서드</td>
</tr>
<tr>
<td>once(이벤트명, 콜백)</td>
<td>한 번만 실행되는 이벤트. 한 번 실행된 이후에는 몇번을 호출하던 실행되지 않음</td>
</tr>
<tr>
<td>removeAllListeners(이벤트명)</td>
<td>이벤트에 연결된 모든 이벤트 리스너 제거</td>
</tr>
<tr>
<td>off(이벤트명, 콜백)</td>
<td>removeAllListeners와 같은 기능을 함</td>
</tr>
<tr>
<td>listenerCount(이벤트명)</td>
<td>현재 리스너가 몇 개 연결되어 있는지 확인함</td>
</tr>
</tbody>
</table><h1 id="에러를-처리하는-방법">3.8 에러를 처리하는 방법</h1>
<p>노드는 싱글스레드이므로 특히 예외를 잘 잡아야 한다.<br>
보통은 try - catch문을 사용하여 에러를 처리한다.</p>
<h4 id="사용자가-직접-지정하는-error">사용자가 직접 지정하는 error</h4>
<pre><code>setInterval(() =&gt; {
	console.log('시작');
	try{
		throw new Error('서버를 고장내주마!');
	} catch (err) {
		console.log(err);
	}
}, 1000);
</code></pre>
<h4 id="노드-자체에서-잡아주는-에러">노드 자체에서 잡아주는 에러</h4>
<pre><code>const fs = require('fs');

setInterval(()=&gt;{
	fs.unlink('./aasdasdsv.js',(err)=&gt;{
		if(err){
			console.log(err);
		}
	});
}, 1000);
</code></pre>
<p>실행 중인 프로세스는 멈추지 않고 1초마다 에러 뱉음<br>
에러를 throw하고 try-catch를 통해 잡아주지 않으면 프로세스가 중지되므로, 반드시 에러를 처리해 줘야 함</p>
<h4 id="예측-불가능한-에러">예측 불가능한 에러</h4>
<pre><code>process.on('uncaughtException', (err) =&gt;{
	console.error('예기치 못한 에러', err);
});

setInterval(() =&gt; {
	 throw new Error('서버 중지!');
	}, 1000);
setTimeout(() =&gt; {
	console.log('실행됩니다');
},2000);

## 결과
서버를 고장내주마!
~~에러정보~~
실행됩니다.
</code></pre>
<p><em>uncaughtException</em> 이벤트 리스너를 사용하여 에러를 처리하였다.<br>
인터벌만 멈추고 나머지는 제대로 실행됨.</p>
<p>어찌 보면 <em>uncaughtException</em> 을 통해 모든 에러를 처리할 수 있을 것 같지만, 노드의 docs를 읽어보면, 이 리스너를 최후의 보루로 사용하라고 되어 있다. 이 핸들러를 통해 오류를 catch하더라도, 그 뒤의 프로세스가 정상적으로 작동할지 보장할 수 없기 때문이다.<br>
그래서 로그 기록정도만 한 후 process.exit()등을 통해 종료시켜 주어야 한다.<br>
운영중인 서버에서 프로세스가 종료되었을 때 다시 시작하는 방법이 있다.(15.1.5절)</p>

